### ISSUE TITLE
true server-side prepared statement

### ISSUE THREAD

**Issue by enginekit** [SharpConnect/SharpConnect.MySql#19]
for true server-side prepared statement
see node-mysql2 
1. https://github.com/sidorares/node-mysql2/tree/master/lib/packets
2. https://github.com/sidorares/node-mysql2/blob/master/lib/packets/prepare_statement.js
3. https://github.com/sidorares/node-mysql2/blob/master/lib/packets/prepared_statement_header.js
4. https://github.com/sidorares/node-mysql2/blob/master/lib/packets/close_statement.js

discussion detail :  
(mr Felix's node-mysql dose not implement the server-side prepared statement)

https://github.com/felixge/node-mysql/issues/274

**Comment by enginekit** [comment]
I think it is not hard for you @brezza27 :+1: 
just a few commands and packets

**Comment by sidorares** [comment]
let me know if you need any help :)

**Comment by enginekit** [comment]
@sidorares  :+1:

**Comment by enginekit** [comment]
see 6ae1b555af96ef550d0ba679672bb61a28aa1074
