### ISSUE TITLE
CommandParams : how about ulong, uint ?

### ISSUE THREAD

**Issue by enginekit** [SharpConnect/SharpConnect.MySql#25]

**Comment by brezza92** [comment]
MySql column types haven't any unsigned value types.
reference : https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-Protocol::ColumnType

**Comment by enginekit** [comment]
please see this
https://dev.mysql.com/doc/refman/5.0/en/integer-types.html

**Comment by enginekit** [comment]
@brezza27 
help me fix this ...
0ed1914df91e1cff35e3551cbeb5e341cbc14f5c

**Comment by brezza92** [comment]
Ok, I'm already fixed it.
899686342d5f0e1603622140720aecae2485949e

**Comment by enginekit** [comment]
@brezza27 
 T_FloatingRange() failed
"Illegal double '1.79769313486232E+308' value found during parsing"

**Comment by brezza92** [comment]
Oh sorry, I'm just forget 'cmd.Prepare();' before, but decimal it has some problem and I'm try finding solution to solve it.

**Comment by enginekit** [comment]
d1618ec1a3a85b20cd21c73138275a03e0584bc3
