### ISSUE TITLE
reimplement  cancel query command

### ISSUE THREAD

**Issue by enginekit** [SharpConnect/SharpConnect.MySql#8]
I think we can cancel query operation.
see https://dev.mysql.com/doc/refman/5.0/en/kill.html

"If you have the PROCESS privilege, you can see all threads. If you have the SUPER privilege, you can kill all threads and statements. Otherwise, you can see and kill only your own threads and statements."

:)

**Comment by brezza92** [comment]
Ok, I reimplement finished.
